/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type AdditionalServicePaymentType = typeof AdditionalServicePaymentType[keyof typeof AdditionalServicePaymentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdditionalServicePaymentType = {
  one_time: 'one_time',
  monthly: 'monthly',
} as const;
