/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type AdditionalServiceOption = typeof AdditionalServiceOption[keyof typeof AdditionalServiceOption];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdditionalServiceOption = {
  video_review: 'video_review',
  invite_manager: 'invite_manager',
  training_reps: 'training_reps',
  place_order: 'place_order',
  select_factory: 'select_factory',
  online_b2b: 'online_b2b',
  custom_order: 'custom_order',
} as const;
