/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type AdditionalServicePaymentType = typeof AdditionalServicePaymentType[keyof typeof AdditionalServicePaymentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdditionalServicePaymentType = {
  free: 'free',
  one_time: 'one_time',
  daily: 'daily',
  monthly: 'monthly',
  weekly: 'weekly',
  yearly: 'yearly',
  quarterly: 'quarterly',
  half_yearly: 'half_yearly',
} as const;
