/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type AdditionalServiceType = typeof AdditionalServiceType[keyof typeof AdditionalServiceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdditionalServiceType = {
  customer: 'customer',
  manufacturer: 'manufacturer',
} as const;
