/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { AdditionalServiceType } from './additionalServiceType';
import type { AdditionalServiceOption } from './additionalServiceOption';
import type { AdditionalServicePaymentType } from './additionalServicePaymentType';

export interface AdditionalService {
  readonly id?: number;
  created_at?: string;
  readonly updated_at?: string;
  type?: AdditionalServiceType;
  option?: AdditionalServiceOption;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @nullable */
  description?: string | null;
  price: string;
  /** @nullable */
  price_sum?: string | null;
  /** @nullable */
  readonly offerta_file?: string | null;
  payment_type?: AdditionalServicePaymentType;
  is_active?: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
}
