/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { AdditionalServiceType } from './additionalServiceType';
import type { AdditionalServiceOption } from './additionalServiceOption';

export interface AdditionalService {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @nullable */
  description?: string | null;
  price: string;
  type?: AdditionalServiceType;
  option?: AdditionalServiceOption;
  readonly is_apply?: boolean;
}
