/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type ApiV1ManufacturerListListParams = {
/**
 * A search term.
 */
search?: string;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
};
