/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type ApiV1PackageListListParams = {
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
};
