/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type ApiV1ManufacturerListListParams = {
    /**
     * A search term.
     */
    search?: string;
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string;
    /**
     * Product segment filter.
     */
    product_segment?: string;
    /**
     * Minimum order quantity filter.
     */
    min_order_quantity?: string;
    /**
     * Page parameter for infinite queries.
     */
    pageParam?: string;
};
