/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type ApiV1ServiceListListParams = {
    /**
     * A search term.
     */
    search?: string;
    /**
     * Service type filter.
     */
    type?: 'manufacturer' | 'customer';
    /**
     * Page parameter for infinite queries.
     */
    pageParam?: string;
};
