/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { ApplicationListStatus } from './applicationListStatus';

export interface ApplicationList {
  readonly id?: number;
  /** @nullable */
  manufacturer?: number | null;
  /** @nullable */
  service?: number | null;
  readonly status?: ApplicationListStatus;
  readonly created_at?: string;
}
