/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { ApplicationCreateStatus } from './applicationCreateStatus';

export interface ApplicationCreate {
  readonly id?: number;
  created_at?: string;
  readonly updated_at?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  segment?: string | null;
  /** @nullable */
  work_purpose?: string | null;
  /** @nullable */
  interested_factories?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  quantity_to_see?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  planned_stay_days?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  planned_arrival_dates?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  needs_tourist_program?: string | null;
  /** @nullable */
  product_description?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  order_volume?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  production_delivery_time?: string | null;
  /** @nullable */
  special_requirements?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  budget_estimated_price?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  segment_category?: string | null;
  /** @nullable */
  additional_notes?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  contact_phone?: string | null;
  /**
   * @maxLength 254
   * @nullable
   */
  contact_email?: string | null;
  status?: ApplicationCreateStatus;
  /** @nullable */
  user?: number | null;
  /** @nullable */
  manufacturer?: number | null;
  /** @nullable */
  customer?: number | null;
  /** @nullable */
  service?: number | null;
  /** @nullable */
  package?: number | null;
}
