/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface CustomerCreate {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  full_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  position: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  company_name: string;
  /** @nullable */
  website?: string | null;
  /** @minLength 1 */
  legal_address: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  marketplace_brand: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  annual_order_volume: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  segment: string;
  /**
   * @minLength 1
   * @maxLength 250
   */
  cooperation_terms: string;
  /**
   * @minLength 1
   * @maxLength 250
   */
  payment_terms: string;
  /**
   * @maxLength 30
   * @nullable
   */
  phone?: string | null;
  readonly created_at?: string;
  user: number;
}
