/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { ManufacturerDetailStatus } from './manufacturerDetailStatus';
import type { Category } from './category';
import type { SegmentList } from './segmentList';
import type { ManufacturerCertificate } from './manufacturerCertificate';
import type { ManufacturerCompanyImage } from './manufacturerCompanyImage';

export interface ManufacturerDetail {
  readonly id?: number;
  user: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  company_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  market_experience: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  full_name: string;
  /**
   * @maxLength 255
   * @nullable
   */
  addition_fio?: string | null;
  /**
   * @minLength 1
   * @maxLength 100
   */
  position: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  min_order_quantity: string;
  /** @minLength 1 */
  commercial_offer_text: string;
  /** @nullable */
  readonly commercial_offer?: string | null;
  /** @minLength 1 */
  production_address: string;
  /** @minLength 1 */
  office_address: string;
  /**
   * @maxLength 100
   * @nullable
   */
  website?: string | null;
  has_quality_control?: boolean;
  has_crm?: boolean;
  has_erp?: boolean;
  has_gemini_gerber?: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  employee_count: number;
  owns_building: boolean;
  has_power_issues: boolean;
  has_credit_load: boolean;
  /** @minLength 1 */
  organization_structure: string;
  /** @minLength 1 */
  equipment_info: string;
  /**
   * @maxLength 30
   * @nullable
   */
  phone?: string | null;
  status?: ManufacturerDetailStatus;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
  /**
   * @maxLength 20
   * @nullable
   */
  inn?: string | null;
  /**
   * @maxLength 300
   * @nullable
   */
  company_rating?: string | null;
  /**
   * @maxLength 300
   * @nullable
   */
  annual_export_turnover?: string | null;
  /** @nullable */
  export_countries?: string | null;
  /** @nullable */
  worked_brands?: string | null;
  /** @nullable */
  readonly logo?: string | null;
  category: Category[];
  product_segment: SegmentList[];
  sertificates: ManufacturerCertificate[];
  images: ManufacturerCompanyImage[];
}
