/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface ManufacturerDetail {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  company_name: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  full_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  min_order_quantity: string;
  /** @minLength 1 */
  office_address: string;
  /**
   * @maxLength 100
   * @nullable
   */
  website?: string | null;
  has_crm?: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  employee_count: number;
}
