/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface ManufacturerCompanyImage {
  readonly id?: number;
  readonly image?: string;
}
