/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { ManufacturerCreateStatus } from './manufacturerCreateStatus';

export interface ManufacturerCreate {
  readonly id?: number;
  created_at?: string;
  readonly updated_at?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  company_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  market_experience: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  full_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  position: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  min_order_quantity: string;
  /** @minLength 1 */
  commercial_offer_text: string;
  /** @nullable */
  readonly commercial_offer?: string | null;
  /** @minLength 1 */
  production_address: string;
  /** @minLength 1 */
  office_address: string;
  /**
   * @maxLength 100
   * @nullable
   */
  website?: string | null;
  has_quality_control?: boolean;
  has_crm?: boolean;
  has_erp?: boolean;
  has_gemini_gerber?: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  employee_count: number;
  owns_building: boolean;
  has_power_issues: boolean;
  has_credit_load: boolean;
  /** @minLength 1 */
  organization_structure: string;
  /** @minLength 1 */
  equipment_info: string;
  /**
   * @maxLength 30
   * @nullable
   */
  phone?: string | null;
  status?: ManufacturerCreateStatus;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
  user: number;
  product_segment: number[];
  sertificates?: number[];
}
