/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface ManufacturerCertificate {
  readonly id?: number;
  created_at?: string;
  readonly updated_at?: string;
  readonly certificate?: string;
  /** @nullable */
  certificate_received_date?: string | null;
  /** @nullable */
  certificate_expiration_date?: string | null;
}
