/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { OfferUpdateStatus } from './offerUpdateStatus';

export interface OfferUpdate {
  readonly id?: number;
  created_at?: string;
  readonly updated_at?: string;
  status?: OfferUpdateStatus;
  user: number;
  /** @nullable */
  application?: number | null;
  /** @nullable */
  manufacturer?: number | null;
  /** @nullable */
  customer?: number | null;
  service: number;
}
