/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type OfferListStatus = typeof OfferListStatus[keyof typeof OfferListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferListStatus = {
  chosen: 'chosen',
  not_chosen: 'not_chosen',
} as const;
