/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface PackageList {
  readonly id?: number;
  created_at?: string;
  readonly updated_at?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  readonly banner?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
  /**
   * @maxLength 100
   * @nullable
   */
  contact_manager?: string | null;
}
