/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { TransactionCreateProvider } from './transactionCreateProvider';

export interface TransactionCreate {
  user: number;
  provider?: TransactionCreateProvider;
  /** @nullable */
  reference?: string | null;
  /** @nullable */
  additional_service?: number | null;
  /**
   * @maxLength 200
   * @nullable
   */
  redirect_url?: string | null;
}
