/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type TransactionCreateProvider = typeof TransactionCreateProvider[keyof typeof TransactionCreateProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionCreateProvider = {
  paylov: 'paylov',
  payme: 'payme',
  click: 'click',
} as const;
