/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface AdditionalService {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @nullable */
  description?: string | null;
  price: string;
  readonly is_apply?: boolean;
}
