/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { ApplicationAdditionalServiceStatus } from './applicationAdditionalServiceStatus';

export interface ApplicationAdditionalService {
  readonly id?: number;
  manufacturer: number;
  service: number;
  readonly status?: ApplicationAdditionalServiceStatus;
  readonly created_at?: string;
}
