/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type ApplicationAdditionalServiceStatus = typeof ApplicationAdditionalServiceStatus[keyof typeof ApplicationAdditionalServiceStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationAdditionalServiceStatus = {
  in_progress: 'in_progress',
  approved: 'approved',
  paid: 'paid',
} as const;
