/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface Login {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}
