/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface ManufacturerList {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  company_name: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  full_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  product_segment: string;
}
