/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type ManufacturerListStatus = typeof ManufacturerListStatus[keyof typeof ManufacturerListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManufacturerListStatus = {
  in_progress: 'in_progress',
  approved: 'approved',
  paid: 'paid',
} as const;
