/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type OfferUpdateStatus = typeof OfferUpdateStatus[keyof typeof OfferUpdateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferUpdateStatus = {
  chosen: 'chosen',
  not_chosen: 'not_chosen',
} as const;
