/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { OfferUpdate } from './offerUpdate';

export type OfferUpdateBody = OfferUpdate;
