/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import type { PackageDetailType } from './packageDetailType';
import type { PackageItemList } from './packageItemList';

export interface PackageDetail {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @nullable */
  readonly banner?: string | null;
  type?: PackageDetailType;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  order?: number;
  items: PackageItemList[];
}
