/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type PackageListType = typeof PackageListType[keyof typeof PackageListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageListType = {
  start: 'start',
  growth: 'growth',
  export: 'export',
} as const;
