/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export type PackageDetailType = typeof PackageDetailType[keyof typeof PackageDetailType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageDetailType = {
  start: 'start',
  growth: 'growth',
  export: 'export',
} as const;
