/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */

export interface Slider {
  readonly id?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /** @minLength 1 */
  description: string;
  readonly image?: string;
  is_active?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
}
