/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Documentation
 * API for your Django project
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const docsList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<null>(
      {url: `/docs/`, method: 'GET', signal
    },
      options);
    }
  

export const getDocsListQueryKey = () => {
    return [`/docs/`] as const;
    }

    
export const getDocsListInfiniteQueryOptions = <TData = Awaited<ReturnType<typeof docsList>>, TError = unknown>( options?: { query?:UseInfiniteQueryOptions<Awaited<ReturnType<typeof docsList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDocsListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof docsList>>> = ({ signal }) => docsList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof docsList>>, TError, TData> & { queryKey: QueryKey }
}

export type DocsListInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof docsList>>>
export type DocsListInfiniteQueryError = unknown



export function useDocsListInfinite<TData = Awaited<ReturnType<typeof docsList>>, TError = unknown>(
  options?: { query?:UseInfiniteQueryOptions<Awaited<ReturnType<typeof docsList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDocsListInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions ) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getDocsListQueryOptions = <TData = Awaited<ReturnType<typeof docsList>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof docsList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDocsListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof docsList>>> = ({ signal }) => docsList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof docsList>>, TError, TData> & { queryKey: QueryKey }
}

export type DocsListQueryResult = NonNullable<Awaited<ReturnType<typeof docsList>>>
export type DocsListQueryError = unknown



export function useDocsList<TData = Awaited<ReturnType<typeof docsList>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof docsList>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDocsListQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



